# _config.yml
# ç½‘ç«™æ ¸å¿ƒé…ç½®
title: Weiwei-Geo           # ä½ çš„ç½‘ç«™æ ‡é¢˜
description: "ç”Ÿå‘½æ˜¯ä¸€æ£µé•¿æ»¡å¯èƒ½çš„æ ‘ğŸŒ²"          # ç½‘ç«™æè¿°
baseurl: ""                       # å¦‚æœä½ çš„ç«™ç‚¹ä¸æ˜¯æ‰˜ç®¡åœ¨åŸŸåæ ¹ç›®å½•ï¼Œè¯·å¡«å†™å­è·¯å¾„ï¼Œå¦‚ "/blog"ã€‚é€šå¸¸ä¸ªäººä¸»é¡µç•™ç©ºã€‚
url: "https://weiwei-geo.github.io" # è¯·æ›¿æ¢ä¸ºä½ çš„ GitHub Pages åœ°å€
theme: jekyll-theme-minimal        # ä½¿ç”¨ Minimal ä¸»é¢˜

# GitHub Pages æ„å»ºè®¾ç½®
plugins:
  - jekyll-feed                   # å¯é€‰ï¼šä¸ºæ–‡ç« ç”Ÿæˆ RSS è®¢é˜…æº
  - jekyll-seo-tag                # å¯é€‰ï¼šæ·»åŠ  SEO ä¼˜åŒ–æ ‡ç­¾

avatar: "/assets/images/avatar.jpg"

toc: true # å…¨å±€å¯ç”¨æ–‡ç« ç›®å½•

# ç¤¾åª’
social:
  name:
  email:
  links:
    -""

# è‡ªå®šä¹‰å˜é‡ï¼ˆå¯é€‰ï¼Œå¯åœ¨é¡µé¢ä¸­ç”¨ {{ site.my_custom_var }} å¼•ç”¨ï¼‰
# è®¾ç½®é»˜è®¤å¸ƒå±€ï¼ˆå¯é€‰ï¼‰
defaults:
  - scope:
      path: ""            # è·¯å¾„ä¸ºç©ºè¡¨ç¤ºé€‚ç”¨äºæ‰€æœ‰æ–‡ä»¶
      type: "posts"       # æŒ‡å®šç±»å‹ä¸ºâ€œæ–‡ç« â€
    values:
      layout: "post"      # ä¸ºæ‰€æœ‰æ–‡ç« åº”ç”¨â€œpostâ€å¸ƒå±€
      author: "weiwei"    # ä¸ºæ‰€æœ‰æ–‡ç« è®¾ç½®é»˜è®¤ä½œè€…
